---

- name: Copy private key
  copy:
      src: "{{ keyfile }}"
      dest: "~/.ssh/keyfile"
      mode: 0400

- name: Git Clone
  git:
      repo: "git clone https://github.com/sanjeev3d/Testrepo.git"
      dest: "/var/www/html/test"
      update : yes
      clone : yes
      version: "{{ branch }}"
      accept_hostkey: yes
      key_file: "~/.ssh/keyfile"
      force: yes
